#include "include/make.h"
#include "include/graph.h"

static void subst_cmd_for_make(const char *in, char *out, size_t n)
{
    size_t o = 0;
    for (size_t i = 0; in[i] && o + 1 < n; ) {
        if (in[i] == '$') {
            if (in[i + 1] == '$') {
                if (o + 2 < n) {
                    out[o++] = '$';
                    out[o++] = '$';
                }
                i += 2;
                continue;
            }
            if (strncmp(in + i, "$out", 4) == 0) {
                if (o + 2 < n) {
                    out[o++] = '$';
                    out[o++] = '@';
                }
                i += 4;
                continue;
            }
            if (strncmp(in + i, "$in", 3) == 0) {
                if (o + 2 < n) {
                    out[o++] = '$';
                    out[o++] = '<';
                }
                i += 3;
                continue;
            }
        }
        out[o++] = in[i++];
    }
    out[o] = '\0';
}

static int make_uses_pattern(const Graph *g)
{
    if (g->count != 1 || g->cmd_count > 0)
        return 0;
    Target *t = &g->targets[0];
    if (t->order_deps.count > 0)
        return 0;
    for (size_t i = 0; i < t->sources.count; i++)
        if (!is_c_source(t->sources.items[i]) ||
            strchr(t->sources.items[i], '/'))
            return 0;
    return 1;
}

int emit_makefile(const Graph *g, const char *cc, const char *ar,
                  const char *path)
{
    if (g->count == 0 && g->cmd_count == 0) {
        diag("no targets declared; nothing to emit");
        return 1;
    }
    FILE *f = fopen(path, "w");
    if (!f) {
        diag("cannot write %s", path);
        return 1;
    }

    const char *as_bin = getenv("AS");
    if (!as_bin || !*as_bin)
        as_bin = "as";

    int pattern = make_uses_pattern(g);
    char pfx[2048];
    dir_prefix(path, pfx, sizeof(pfx));

    fprintf(f, "# Makefile - generated by thorn " THORN_VERSION
               ", do not edit\n");
    fprintf(f, "# project: %s (deterministic: same graph and "
               "environment, same bytes)\n\n", g->proj);
    fprintf(f, "thorn_project = %s\n", g->proj);
    fprintf(f, "CC = %s\n", cc);
    fprintf(f, "AS = %s\n", as_bin);
    fprintf(f, "AR = %s\n\n", ar);

    /* per-target variables */
    for (size_t i = 0; i < g->count; i++) {
        Target *t = &g->targets[i];
        char obj[1024];
        fprintf(f, "%s_OBJS =", t->name);
        for (size_t s = 0; s < t->sources.count; s++) {
            const char *src = t->sources.items[s];
            if (!is_buildable_source(src))
                continue;
            if (pattern) {
                snprintf(obj, sizeof(obj), "%s", src);
                obj[strlen(obj) - 1] = 'o';
            } else {
                obj_name(t, src, obj, sizeof(obj));
            }
            fprintf(f, " %s%s", pfx, obj);
        }
        fprintf(f, "\n");

        SBuf ctext;
        flags_text(t, &ctext);
        fprintf(f, "%s_CFLAGS = %s\n", t->name, ctext.buf);
        sb_free(&ctext);

        SBuf atext;
        asflags_text(t, &atext);
        fprintf(f, "%s_ASFLAGS = %s\n", t->name, atext.buf);
        sb_free(&atext);

        SBuf lt;
        ldflags_text(t, &lt);
        fprintf(f, "%s_LDFLAGS = %s\n\n", t->name, lt.buf);
        sb_free(&lt);
    }

    /* all (default rule) */
    if (g->count > 0) {
        fprintf(f, "all:");
        for (size_t i = 0; i < g->count; i++) {
            char tname[2048], aname[512];
            artifact_name(&g->targets[i], aname, sizeof(aname));
            out_name(tname, sizeof(tname), pfx, aname);
            fprintf(f, " %s", tname);
        }
        fprintf(f, "\n\n");
    }

    /* custom command rules */
    for (size_t i = 0; i < g->cmd_count; i++) {
        const Command *c = &g->commands[i];
        char cout[2048];
        out_name(cout, sizeof(cout), pfx, c->output);
        char make_cmd[2048];
        subst_cmd_for_make(c->command, make_cmd, sizeof(make_cmd));
        if (c->input[0])
            fprintf(f, "%s: %s\n", cout, c->input);
        else
            fprintf(f, "%s:\n", cout);
        fprintf(f, "\t%s\n\n", make_cmd);
    }

    /* link rules */
    for (size_t i = 0; i < g->count; i++) {
        Target *t = &g->targets[i];
        char tname[2048], aname[512];
        artifact_name(t, aname, sizeof(aname));
        out_name(tname, sizeof(tname), pfx, aname);
        fprintf(f, "%s: $(%s_OBJS)", tname, t->name);
        for (size_t s = 0; s < t->sources.count; s++)
            if (!is_buildable_source(t->sources.items[s]))
                fprintf(f, " %s", t->sources.items[s]);
        for (size_t d = 0; d < t->order_deps.count; d++)
            fprintf(f, " %s", t->order_deps.items[d]);
        fprintf(f, "\n");
        if (t->type == THORN_STATIC_LIB) {
            fprintf(f, "\t$(AR) rcs $@ $^\n\n");
        } else if (t->type == THORN_SHARED_LIB) {
            if (t->ldflags.count > 0)
                fprintf(f, "\t$(CC) -shared $^ $(%s_LDFLAGS) -o $@\n\n",
                        t->name);
            else
                fprintf(f, "\t$(CC) -shared $^ -o $@\n\n");
        } else {
            if (t->ldflags.count > 0)
                fprintf(f, "\t$(CC) $^ $(%s_LDFLAGS) -o $@\n\n",
                        t->name);
            else
                fprintf(f, "\t$(CC) $^ -o $@\n\n");
        }
    }

    /* compile rules */
    if (pattern) {
        Target *t = &g->targets[0];
        fprintf(f, "%s%%.o: %%.c\n", pfx);
        if (t->cflags.count > 0 || t->includes.count > 0)
            fprintf(f, "\t$(CC) $(%s_CFLAGS) -MMD -MP -c $< -o $@\n\n",
                    t->name);
        else
            fprintf(f, "\t$(CC) -MMD -MP -c $< -o $@\n\n");
    } else {
        for (size_t i = 0; i < g->count; i++) {
            Target *t = &g->targets[i];
            char obj[1024];
            for (size_t s = 0; s < t->sources.count; s++) {
                const char *src = t->sources.items[s];
                if (!is_buildable_source(src))
                    continue;
                SourceKind sk = t->source_kinds ? t->source_kinds[s] : classify_source(src);
                obj_name(t, src, obj, sizeof(obj));
                fprintf(f, "%s%s: %s", pfx, obj, src);
                for (size_t d = 0; d < t->order_deps.count; d++)
                    fprintf(f, " %s", t->order_deps.items[d]);
                fprintf(f, "\n");
                if (sk == SRC_ASM_RAW) {
                    if (t->asflags.count > 0)
                        fprintf(f, "\t$(AS) $(%s_ASFLAGS) -c %s -o $@\n\n",
                                t->name, src);
                    else
                        fprintf(f, "\t$(AS) -c %s -o $@\n\n", src);
                } else if (sk == SRC_ASM_CPP) {
                    fprintf(f, "\t$(CC) -MMD -MP $(%s_ASFLAGS) $(%s_CFLAGS) -c %s -o $@\n\n",
                            t->name, t->name, src);
                } else {
                    if (t->cflags.count > 0 || t->includes.count > 0)
                        fprintf(f, "\t$(CC) $(%s_CFLAGS) -MMD -MP -c %s -o $@\n\n",
                                t->name, src);
                    else
                        fprintf(f, "\t$(CC) -MMD -MP -c %s -o $@\n\n", src);
                }
            }
        }
    }

    /* clean */
    fprintf(f, "clean:\n\trm -f");
    for (size_t i = 0; i < g->count; i++) {
        Target *t = &g->targets[i];
        char obj[1024];
        for (size_t s = 0; s < t->sources.count; s++) {
            const char *src = t->sources.items[s];
            if (!is_buildable_source(src))
                continue;
            SourceKind sk = t->source_kinds ? t->source_kinds[s] : classify_source(src);
            if (pattern) {
                snprintf(obj, sizeof(obj), "%s", src);
                obj[strlen(obj) - 1] = 'o';
                fprintf(f, " %s%s.d %s%s", pfx, obj, pfx, obj);
            } else {
                obj_name(t, src, obj, sizeof(obj));
                if (sk == SRC_ASM_RAW) {
                    fprintf(f, " %s%s", pfx, obj);
                } else {
                    char dep[1024];
                    snprintf(dep, sizeof(dep), "%s", obj);
                    dep[strlen(dep) - 1] = 'd';
                    fprintf(f, " %s%s %s%s", pfx, obj, pfx, dep);
                }
            }
        }
        char tname[2048], aname[512];
        artifact_name(t, aname, sizeof(aname));
        out_name(tname, sizeof(tname), pfx, aname);
        fprintf(f, " %s", tname);
    }
    for (size_t i = 0; i < g->cmd_count; i++) {
        char cout[2048];
        out_name(cout, sizeof(cout), pfx, g->commands[i].output);
        fprintf(f, " %s", cout);
    }
    fprintf(f, "\n\n");

    fprintf(f, ".PHONY: all clean\n\n");

    /* dependency fragments emitted by -MMD */
    fprintf(f, "-include");
    for (size_t i = 0; i < g->count; i++) {
        Target *t = &g->targets[i];
        char dep[1024];
        for (size_t s = 0; s < t->sources.count; s++) {
            const char *src = t->sources.items[s];
            if (!is_buildable_source(src))
                continue;
            SourceKind sk = t->source_kinds ? t->source_kinds[s] : classify_source(src);
            if (sk == SRC_ASM_RAW)
                continue;
            if (pattern) {
                snprintf(dep, sizeof(dep), "%s", src);
                dep[strlen(dep) - 1] = 'd';
            } else {
                obj_name(t, src, dep, sizeof(dep));
                dep[strlen(dep) - 1] = 'd';
            }
            fprintf(f, " %s%s", pfx, dep);
        }
    }
    fprintf(f, "\n");

    fclose(f);
    return 0;
}
