#include "include/ninja.h"
#include "include/graph.h"

int emit_ninja(const Graph *g, const char *cc, const char *ar,
               const char *path)
{
    if (g->count == 0 && g->cmd_count == 0) {
        diag("no targets declared; nothing to emit");
        return 1;
    }
    FILE *f = fopen(path, "w");
    if (!f) {
        diag("cannot write %s", path);
        return 1;
    }

    const char *as_bin = getenv("AS");
    if (!as_bin || !*as_bin)
        as_bin = "as";

    char pfx[2048];
    dir_prefix(path, pfx, sizeof(pfx));

    fprintf(f, "# build.ninja - generated by thorn " THORN_VERSION
               ", do not edit\n");
    fprintf(f, "# project: %s (deterministic: same graph and "
               "environment, same bytes)\n\n", g->proj);
    fprintf(f, "ninja_required_version = 1.3\n\n");
    fprintf(f, "thorn_project = %s\n", g->proj);
    fprintf(f, "cc = %s\n", cc);
    fprintf(f, "as = %s\n", as_bin);
    fprintf(f, "ar = %s\n\n", ar);

    /* toolchain rules */
    fprintf(f, "rule cc\n");
    fprintf(f, "  command = $cc $cflags -MMD -MF $out.d -c $in -o $out\n");
    fprintf(f, "  depfile = $out.d\n");
    fprintf(f, "  deps = gcc\n");
    fprintf(f, "  description = cc $in\n\n");

    fprintf(f, "rule as\n");
    fprintf(f, "  command = $as $asflags -c $in -o $out\n");
    fprintf(f, "  description = as $in\n\n");

    fprintf(f, "rule as_cpp\n");
    fprintf(f, "  command = $cc -MD -MF $out.d $asflags $cflags -c $in -o $out\n");
    fprintf(f, "  depfile = $out.d\n");
    fprintf(f, "  deps = gcc\n");
    fprintf(f, "  description = as_cpp $in\n\n");

    fprintf(f, "rule link\n");
    fprintf(f, "  command = $cc $in $ldflags -o $out\n");
    fprintf(f, "  description = link $out\n\n");

    fprintf(f, "rule solink\n");
    fprintf(f, "  command = $cc -shared $in $ldflags -o $out\n");
    fprintf(f, "  description = shared $out\n\n");

    fprintf(f, "rule ar\n");
    fprintf(f, "  command = rm -f $out && $ar rcs $out $in\n");
    fprintf(f, "  description = ar $out\n\n");

    /* custom command rules and edges */
    for (size_t i = 0; i < g->cmd_count; i++) {
        const Command *c = &g->commands[i];
        char cout[2048];
        out_name(cout, sizeof(cout), pfx, c->output);
        fprintf(f, "# custom command %zu (%s)\n", i + 1, c->output);
        fprintf(f, "rule cmd_%zu\n", i + 1);
        fprintf(f, "  command = %s\n", c->command);
        fprintf(f, "  description = %s\n\n", c->command);
        if (c->input[0])
            fprintf(f, "build %s: cmd_%zu %s\n\n", cout, i + 1, c->input);
        else
            fprintf(f, "build %s: cmd_%zu\n\n", cout, i + 1);
    }

    /* default target aggregation */
    if (g->count > 0) {
        char all[2048];
        out_name(all, sizeof(all), pfx, "thorn_all");
        fprintf(f, "build %s: phony", all);
        for (size_t i = 0; i < g->count; i++) {
            char tgt[2048], aname[512];
            artifact_name(&g->targets[i], aname, sizeof(aname));
            out_name(tgt, sizeof(tgt), pfx, aname);
            fprintf(f, " %s", tgt);
        }
        fprintf(f, "\n");
        fprintf(f, "default %s\n\n", all);
    }

    for (size_t i = 0; i < g->count; i++) {
        Target *t = &g->targets[i];
        SBuf ctext;
        flags_text(t, &ctext);
        SBuf atext;
        asflags_text(t, &atext);
        char tname[2048], aname[512], obj[1024];
        artifact_name(t, aname, sizeof(aname));
        out_name(tname, sizeof(tname), pfx, aname);

        fprintf(f, "# target %s (%s)\n", t->name, type_name(t->type));

        for (size_t s = 0; s < t->sources.count; s++) {
            const char *src = t->sources.items[s];
            if (!is_buildable_source(src))
                continue;
            SourceKind sk = t->source_kinds ? t->source_kinds[s] : classify_source(src);
            const char *rule_name = (sk == SRC_ASM_RAW) ? "as"
                                  : (sk == SRC_ASM_CPP) ? "as_cpp"
                                                        : "cc";
            obj_name(t, src, obj, sizeof(obj));
            fprintf(f, "build %s%s: %s %s", pfx, obj, rule_name, src);
            for (size_t d = 0; d < t->order_deps.count; d++)
                fprintf(f, " || %s", t->order_deps.items[d]);
            fprintf(f, "\n");
            if (sk == SRC_ASM_RAW) {
                if (atext.len > 0)
                    fprintf(f, "  asflags = %s\n", atext.buf);
            } else if (sk == SRC_ASM_CPP) {
                if (atext.len > 0)
                    fprintf(f, "  asflags = %s\n", atext.buf);
                if (ctext.len > 0)
                    fprintf(f, "  cflags = %s\n", ctext.buf);
            } else {
                if (ctext.len > 0)
                    fprintf(f, "  cflags = %s\n", ctext.buf);
            }
        }

        const char *rule = t->type == THORN_STATIC_LIB ? "ar"
                        : t->type == THORN_SHARED_LIB ? "solink"
                                                      : "link";
        fprintf(f, "build %s: %s", tname, rule);
        for (size_t s = 0; s < t->sources.count; s++) {
            const char *src = t->sources.items[s];
            if (is_buildable_source(src)) {
                obj_name(t, src, obj, sizeof(obj));
                fprintf(f, " %s%s", pfx, obj);
            } else {
                fprintf(f, " %s", src);
            }
        }
        for (size_t d = 0; d < t->order_deps.count; d++)
            fprintf(f, " | %s", t->order_deps.items[d]);
        fprintf(f, "\n");

        if (t->type != THORN_STATIC_LIB && t->ldflags.count > 0) {
            SBuf lt;
            ldflags_text(t, &lt);
            fprintf(f, "  ldflags = %s\n", lt.buf);
            sb_free(&lt);
        }
        if (pfx[0] != '\0' && strcmp(tname, t->name) != 0) {
            fprintf(f, "build %s: phony %s\n", t->name, tname);
        }
        fprintf(f, "\n");
        sb_free(&ctext);
        sb_free(&atext);
    }

    fclose(f);
    return 0;
}
