#include "include/spec.h"
#include "include/graph.h"

int print_spec(const Graph *g, FILE *out, const char **notes,
               size_t nnotes)
{
    fprintf(out, "# build.thorn - generated by thorn " THORN_VERSION
                 "\n");
    fprintf(out, "# decompiled from an existing build graph; review "
                 "before use\n\n");
    fprintf(out, "engine.project(\"%s\")\n", g->proj);
    if (g->backend[0])
        fprintf(out, "engine.backend(\"%s\")\n", g->backend);
    fprintf(out, "\n");

    for (size_t i = 0; i < g->count; i++) {
        Target *t = &g->targets[i];
        fprintf(out, "engine.add_target(\"%s\", engine.%s)\n",
                t->name, type_const(t->type));
        for (size_t s = 0; s < t->sources.count; s++)
            fprintf(out, "engine.add_source(\"%s\", \"%s\")\n",
                t->name, t->sources.items[s]);
        for (size_t s = 0; s < t->includes.count; s++)
            fprintf(out, "engine.add_include(\"%s\", \"%s\")\n",
                t->name, t->includes.items[s]);
        for (size_t s = 0; s < t->cflags.count; s++)
            fprintf(out, "engine.add_cflag(\"%s\", \"%s\")\n",
                t->name, t->cflags.items[s]);
        for (size_t s = 0; s < t->asflags.count; s++)
            fprintf(out, "engine.add_asflag(\"%s\", \"%s\")\n",
                t->name, t->asflags.items[s]);
        for (size_t s = 0; s < t->ldflags.count; s++)
            fprintf(out, "engine.add_ldflag(\"%s\", \"%s\")\n",
                t->name, t->ldflags.items[s]);
        for (size_t s = 0; s < t->order_deps.count; s++)
            fprintf(out, "engine.add_order_dep(\"%s\", \"%s\")\n",
                t->name, t->order_deps.items[s]);
        fprintf(out, "\n");
    }

    for (size_t i = 0; i < g->cmd_count; i++) {
        Command *c = &g->commands[i];
        fprintf(out, "engine.add_command(\"%s\", \"%s\", \"%s\")\n",
                c->output, c->command, c->input);
    }
    if (g->cmd_count > 0)
        fprintf(out, "\n");

    for (size_t i = 0; i < nnotes; i++)
        fprintf(out, "\n# note: %s\n", notes[i]);
    return 0;
}
